trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'dotnet build'
  displayName: 'Build'

- script: 'dotnet pack --configuration Release'
  displayName: 'Pack'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  # Replace with the version you are using
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Use .NET SDK 3.1.x'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  inputs:
    nuGetServiceConnections: 'dotnetImage'  # Replace with your service connection name

- script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/harikumarpeddakotla7/PipelinetoAWS/_packaging/dotnetImage/nuget/v3/index.json" --api-key $(System.AccessToken)'
  displayName: 'Push NuGet package to Azure Artifacts'
