trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'dotnet build'
  displayName: 'Build'

- script: 'dotnet pack --configuration Release'
  displayName: 'Pack'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  # Replace with the version you are using
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Use .NET SDK 3.1.x'

- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg \
      --source $(Nuget) \  # Change 'Nuget' to 'Nuget' (service connection name)
      --api-key $(apikeyy)  # Change 'apikeyy' to 'apikeyy' (your PAT variable)
  displayName: 'Push NuGet package to Azure Artifacts'
